version: '3'

services:

  esdoc:
    build:
      context: docker/esdoc
    volumes: &volumes
      - ./.sources:/sources
      - ./.docs-esdoc:/docs
      - ./scripts:/scripts:ro

  esdoc2:
    build:
      context: docker/esdoc2
    volumes:
      - ./.sources:/sources
      - ./.docs-esdoc2:/docs
      - ./scripts:/scripts:ro
