version: '3'

services:

  esdoc:
    build:
      context: docker/esdoc
    volumes: &volumes
      - ./.sources:/sources
      - ./.docs-esdoc:/docs
      - ./scripts:/scripts:ro

  esdoc2:
    build:
      context: docker/esdoc2
    volumes:
      - ./.sources:/sources
      - ./.docs-esdoc2:/docs
      - ./scripts:/scripts:ro

  yuidoc:
    build:
      context: docker/yuidoc
    volumes:
      - ./.sources:/sources
      - ./.docs-yuidoc:/docs
      - ./scripts:/scripts:ro

  jsdoc:
    build:
      context: docker/jsdoc
    volumes:
      - ./.sources:/sources
      - ./.docs-jsdoc:/docs
      - ./scripts:/scripts:ro

  docco:
    build:
      context: docker/docco
    volumes:
      - ./.sources:/sources
      - ./.docs-docco:/docs
      - ./scripts:/scripts:ro

  documentationjs:
    build:
      context: docker/documentationjs
    volumes:
      - ./.sources:/sources
      - ./.docs-documentationjs:/docs
      - ./scripts:/scripts:ro